<div id="gitstatus">
  <h3>Git Console Page</h3>

  <?php
    // this the default way to render the form.
    $this->statusForm->setAction($this->url());
    echo $this->statusForm;
  ?>

 <h3>Fill out the following form to commit your change</h3>
  <?php
    $this->commitForm->setAction($this->url());
    echo $this->commitForm->render();
  ?>

  <h3>Raw Result for <?php echo $this->action; ?></h3>
  <pre><?php echo $this->rawResult; ?></pre>
</div>
